function quat_ = euler2quat(euler_angles_)
	e_psi_	= euler_angles_(1);
	e_thta_	= euler_angles_(2);
	e_phi_	= euler_angles_(3);
	quat_	=	[ ...
		cos(e_psi_/2)*cos(e_thta_/2)*cos(e_phi_/2) + sin(e_psi_/2)*sin(e_thta_/2)*sin(e_phi_/2); ...
		cos(e_psi_/2)*cos(e_thta_/2)*sin(e_phi_/2) - sin(e_psi_/2)*sin(e_thta_/2)*cos(e_phi_/2); ...
		cos(e_psi_/2)*sin(e_thta_/2)*cos(e_phi_/2) + sin(e_psi_/2)*cos(e_thta_/2)*sin(e_phi_/2); ...
		sin(e_psi_/2)*cos(e_thta_/2)*cos(e_phi_/2) - cos(e_psi_/2)*sin(e_thta_/2)*sin(e_phi_/2)];

end